"""AI-assisted recon analysis.

Runs after normal phase-6 tools. It creates a compact prompt/context from all
phase artifacts, calls the first configured AI provider, and writes a Markdown
analysis that the web app can preview.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import aiohttp

from models import ToolCategory
from tool_secrets import has_any_ai_api_key
from tools.base import BaseTool, RunResult, clean_tool_output

MAX_ROWS_PER_FILE = 80
MAX_CHARS_PER_FILE = 18_000

GENERIC_AI_PROMPT = """You are a senior bug bounty recon analyst. Use only the provided ShadowGrid recon context.
Return concise Markdown only. Do not invent findings. Prioritize practical, testable attack paths.

Output exactly these sections:
# ShadowGrid AI Recon Analysis
## Executive Summary
- 3-6 bullets, highest signal only.
## Top Priority Subdomains
Table: Priority | Subdomain/URL | Evidence | Why it matters | First tests.
## Attack Paths
For each path: Target, Hypothesis, Evidence, Manual tests, Tool-assisted tests, Stop condition.
## What To Test Next
Checklist grouped by Auth, Access Control/IDOR, XSS/Client-side, SSRF, File/Upload, API, Cloud/Secrets.
## Low Signal / Ignore For Now
- Items that are noisy or not actionable.

Keep it token-efficient. Prefer short commands/checks over generic advice."""


def _read_text(path: Path, limit: int = MAX_CHARS_PER_FILE) -> str:
    if not path.exists() or not path.is_file():
        return ""
    data = path.read_text(errors="replace")
    return data[:limit]


def _read_lines(path: Path, limit: int = MAX_ROWS_PER_FILE) -> list[str]:
    txt = _read_text(path)
    return [line.strip() for line in txt.splitlines() if line.strip()][:limit]


class AIAnalysisTool(BaseTool):
    name = "ai_analysis"
    binary_name = None
    category = ToolCategory.AI
    description = "AI recon analyst: ranks priority subdomains, attack paths and next-test checklist"
    parallel_group = "analysis"

    def availability_error(self) -> str | None:
        if not has_any_ai_api_key():
            return "Configure at least one AI API key in Settings to use AI Analysis"
        return None

    async def run(self, domain: str, out_dir: Path, data_dir: Path,
                  wordlist: str | None, extra: dict) -> RunResult:
        context = self._build_context(domain, out_dir)
        prompt = self._build_prompt(domain, context)

        prompt_path = out_dir / "ai_analysis_prompt.md"
        context_path = out_dir / "ai_analysis_context.json"
        analysis_path = out_dir / "ai_analysis.md"
        prompt_path.write_text(prompt, encoding="utf-8")
        context_path.write_text(json.dumps(context, indent=2), encoding="utf-8")

        try:
            markdown, provider = await self._call_first_available_ai(prompt)
            if not markdown.strip():
                raise RuntimeError("AI provider returned an empty response")
            final = markdown.strip() + f"\n\n---\nGenerated by `{provider}` from ShadowGrid phase outputs.\n"
            analysis_path.write_text(final, encoding="utf-8")
            return RunResult(final, "", 0, 0.0)
        except Exception as exc:
            fallback = self._fallback_markdown(domain, context, prompt, str(exc))
            analysis_path.write_text(fallback, encoding="utf-8")
            # returncode 0 because the Markdown artifact was still produced; expose provider error in the content.
            return RunResult(fallback, "", 0, 0.0)

    def _build_context(self, domain: str, out_dir: Path) -> dict[str, Any]:
        files = {
            "subdomains": "subdomains_merged.txt",
            "dnsx": "dnsx.txt",
            "httpx": "httpx.jsonl",
            "naabu": "naabu.txt",
            "waybackurls": "waybackurls.txt",
            "gau": "gau.txt",
            "katana": "katana.txt",
            "urlfinder": "urlfinder.txt",
            "nuclei": "nuclei_results.jsonl",
            "wpscan": "wpscan.txt",
            "whatweb": "whatweb.txt",
            "google_dorks": "google_dorks.md",
            "alive_urls": "alive_urls.txt",
        }
        context: dict[str, Any] = {"domain": domain, "artifacts": {}}
        for key, filename in files.items():
            path = out_dir / filename
            context["artifacts"][key] = {
                "file": filename,
                "exists": path.exists(),
                "sample": _read_lines(path),
            }

        screenshots_dir = out_dir / "screenshots"
        screenshots = []
        if screenshots_dir.exists():
            for f in sorted(screenshots_dir.rglob("*")):
                if f.is_file() and f.suffix.lower() in {".png", ".jpg", ".jpeg", ".webp"}:
                    screenshots.append(str(f.relative_to(out_dir)))
        context["screenshots"] = screenshots[:80]
        return context

    def _build_prompt(self, domain: str, context: dict[str, Any]) -> str:
        compact = json.dumps(context, separators=(",", ":"))
        return f"{GENERIC_AI_PROMPT}\n\nTarget: {domain}\n\nShadowGrid compact context JSON:\n```json\n{compact}\n```\n"

    def _fallback_markdown(self, domain: str, context: dict[str, Any], prompt: str, error: str) -> str:
        artifacts = context.get("artifacts", {})
        subdomains = artifacts.get("subdomains", {}).get("sample", [])[:20]
        alive_urls = artifacts.get("alive_urls", {}).get("sample", [])[:20]
        nuclei = artifacts.get("nuclei", {}).get("sample", [])[:20]
        dorks = artifacts.get("google_dorks", {}).get("sample", [])[:20]
        return "\n".join([
            f"# ShadowGrid AI Recon Analysis — {domain}",
            "",
            "> AI provider call failed or was unavailable, but ShadowGrid generated the token-efficient prompt and a local triage skeleton.",
            f"> Error: `{clean_tool_output(error)[:300]}`",
            "",
            "## Executive Summary",
            f"- Subdomain sample size in prompt: {len(subdomains)}",
            f"- Alive URL sample size in prompt: {len(alive_urls)}",
            f"- Nuclei finding sample size in prompt: {len(nuclei)}",
            f"- Google dork sample size in prompt: {len(dorks)}",
            "",
            "## Top Priority Subdomains / URLs",
            "| Priority | Target | Evidence | First tests |",
            "|---|---|---|---|",
            *[f"| P2 | `{x}` | Present in live/recon artifacts | Check auth, access control, interesting paths, exposed files |" for x in (alive_urls or subdomains)[:10]],
            "",
            "## Attack Paths",
            "1. **Authenticated surface review** — login/admin/API endpoints → test weak session handling, IDOR, role checks, password reset, OAuth linking.",
            "2. **Content/file exposure** — use generated dorks + URL archives → test backups, configs, indexed documents, directory listings.",
            "3. **API fuzzing** — parameter-heavy archived URLs → test IDOR, mass assignment, SSRF-style URL parameters, unsafe redirects.",
            "",
            "## What To Test Next",
            "- [ ] Review HTTP titles/statuses and prioritize non-404/non-static hosts.",
            "- [ ] Run manual auth/access-control tests on login/admin/API hosts.",
            "- [ ] Open generated Google dorks manually; do not automate Google scraping.",
            "- [ ] Replay high-value archived URLs with owned accounts only.",
            "- [ ] Investigate any Nuclei high/critical results first.",
            "",
            "## Generic Prompt For External AI",
            "```text",
            prompt,
            "```",
        ])

    async def _call_first_available_ai(self, prompt: str) -> tuple[str, str]:
        if os.environ.get("OPENAI_API_KEY"):
            return await self._call_openai(prompt)

        if os.environ.get("ANTHROPIC_API_KEY"):
            return await self._call_anthropic(prompt)

        if os.environ.get("GOOGLE_AI_API_KEY"):
            return await self._call_google(prompt)

        if os.environ.get("DEEPSEEK_API_KEY"):
            return await self._call_openai_compatible(prompt, "deepseek", "https://api.deepseek.com/chat/completions", os.environ["DEEPSEEK_API_KEY"], "deepseek-chat")

        if os.environ.get("GROQ_API_KEY"):
            return await self._call_openai_compatible(prompt, "groq", "https://api.groq.com/openai/v1/chat/completions", os.environ["GROQ_API_KEY"], "llama-3.1-8b-instant")

        raise RuntimeError("No supported AI API key is configured")

    async def _call_openai(self, prompt: str) -> tuple[str, str]:
        return await self._call_openai_compatible(prompt, "openai", "https://api.openai.com/v1/chat/completions", os.environ["OPENAI_API_KEY"], "gpt-4o-mini")

    async def _call_openai_compatible(self, prompt: str, provider: str, url: str, key: str, model: str) -> tuple[str, str]:
        payload = {
            "model": model,
            "temperature": 0.2,
            "max_tokens": 1800,
            "messages": [
                {"role": "system", "content": "You write concise Markdown recon analysis for ethical bug bounty testing."},
                {"role": "user", "content": prompt},
            ],
        }
        headers = {"Authorization": f"Bearer {key}", "Content-Type": "application/json"}
        async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=90)) as session:
            async with session.post(url, headers=headers, json=payload) as resp:
                text = await resp.text()
                if resp.status >= 400:
                    raise RuntimeError(f"{provider} API returned {resp.status}: {text[:500]}")
                data = json.loads(text)
                return data["choices"][0]["message"]["content"], provider

    async def _call_anthropic(self, prompt: str) -> tuple[str, str]:
        payload = {
            "model": "claude-3-5-haiku-latest",
            "max_tokens": 1800,
            "temperature": 0.2,
            "messages": [{"role": "user", "content": prompt}],
        }
        headers = {
            "x-api-key": os.environ["ANTHROPIC_API_KEY"],
            "anthropic-version": "2023-06-01",
            "Content-Type": "application/json",
        }
        async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=90)) as session:
            async with session.post("https://api.anthropic.com/v1/messages", headers=headers, json=payload) as resp:
                text = await resp.text()
                if resp.status >= 400:
                    raise RuntimeError(f"anthropic API returned {resp.status}: {text[:500]}")
                data = json.loads(text)
                return "\n".join(block.get("text", "") for block in data.get("content", []) if block.get("type") == "text"), "anthropic"

    async def _call_google(self, prompt: str) -> tuple[str, str]:
        key = os.environ["GOOGLE_AI_API_KEY"]
        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={key}"
        payload = {"contents": [{"parts": [{"text": prompt}]}], "generationConfig": {"temperature": 0.2, "maxOutputTokens": 1800}}
        async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=90)) as session:
            async with session.post(url, json=payload) as resp:
                text = await resp.text()
                if resp.status >= 400:
                    raise RuntimeError(f"google AI API returned {resp.status}: {text[:500]}")
                data = json.loads(text)
                parts = data.get("candidates", [{}])[0].get("content", {}).get("parts", [])
                return "\n".join(p.get("text", "") for p in parts), "google"

    def parse(self, result: RunResult, domain: str) -> list[dict[str, Any]]:
        out_dir = self.output_dir / domain
        analysis_path = out_dir / "ai_analysis.md"
        prompt_path = out_dir / "ai_analysis_prompt.md"
        content = _read_text(analysis_path, 120_000) or result.stdout
        return [{
            "title": f"AI Recon Analysis — {domain}",
            "domain": domain,
            "markdown": content,
            "path": str(analysis_path.relative_to(self.output_dir)) if analysis_path.exists() else "",
            "prompt_path": str(prompt_path.relative_to(self.output_dir)) if prompt_path.exists() else "",
            "source": "ai_analysis",
        }]
